#!/bin/bash
TARGET="/var/www/html/"
GIT_DIR="/home/ubuntu/mastersite"
BRANCH="master"

echo "Kicking off post-receive from 10.0.0.20 - webserv1"
while read oldrev newrev ref
do
        # only checking out the master (or whatever branch you would like to deploy)
        if [ "$ref" = "refs/heads/$BRANCH" ];
        then
                echo "Ref $ref received. Deploying ${BRANCH} branch to production..."
                git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $BRANCH
        else
                echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server."
        fi
done